[package]
name = "acousticslab-webd"
edition.workspace = true
version.workspace = true
license = "Apache-2.0"
publish = false

[[bin]]
name = "acousticslab-webd"
path = "src/main.rs"

[dependencies]
axum = { workspace = true, features = ["http1", "tokio"] }
hyper = { version = "=1.10.1", features = ["client", "http1"] }
hyper-util = { version = "=0.1.20", features = ["tokio"] }
tower-http = { version = "=0.6.11", features = ["fs", "trace"] }
tokio = { workspace = true, features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "signal",
    "time",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt"] }
anyhow = "=1.0.103"

[lints]
workspace = true
